
import { CartItem, User } from '../types';

/**
 * Generates a WhatsApp URL with order details.
 * Destination number: 201012889478
 */
export const generateWhatsAppLink = (orderId: string, items: CartItem[], total: number, user: User | null) => {
  const phoneNumber = "201012889478"; 
  const itemSummary = items.map(item => `- ${item.name} (${item.selectedColor}) x${item.quantity}: $${item.price * item.quantity}`).join('\n');
  const customerName = user ? user.name : "Guest";
  const customerEmail = user ? user.email : "Not provided";

  const message = `*New Order: #${orderId}*\n\n` +
    `*Customer:* ${customerName}\n` +
    `*Email:* ${customerEmail}\n\n` +
    `*Items:*\n${itemSummary}\n\n` +
    `*Total:* $${total.toFixed(2)}\n\n` +
    `Generated by The T-Shirt Store.`;

  return `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`;
};
